apiVersion: v1
kind: Namespace
metadata:
  name: memory-stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress
  namespace: memory-stress
  labels:
    app: memory-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
      - name: memory-stress
        image: polinux/stress
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "5G", "--vm-hang", "133"]
