apiVersion: v1
kind: Namespace
metadata:
  name: hpa-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: hpa-example
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "8080"
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
        imagePullPolicy: Always
        name: consumer
        resources:
          limits:
            cpu: "700m"
            memory: "500Mi"
          requests:
            cpu: "500m"
            memory: "250Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: hpa-example
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: consumer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumer-mem
  namespace: hpa-example
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: argeu.cluster.com
    http:
      paths:
      - path: /ConsumeMem
        pathType: Prefix
        backend:
          service:
            name: consumer
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumer-cpu
  namespace: hpa-example
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: argeu.cluster.com
    http:
      paths:
      - path: /ConsumeCPU
        pathType: Prefix
        backend:
          service:
            name: consumer
            port:
              number: 80
