apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: echoserver
  namespace: hpa-example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echoserver
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
